language: node_js
node_js:
  - '10.0.0'
os:
  - linux
  - osx

matrix:
  fast_finish: true

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run cucumber; fi
  - npm test
  - npm run release
