language: node_js
node_js:
  - 'lts/*'
os:
  - linux
  - osx

matrix:
  fast_finish: true

services:
  - xvfb

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=:99.0;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run cucumber; fi
  - npm test
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm run release
    else
      npm run release:osx
    fi
