# Site settings
title: Zazu App
description: >
  Zazu is a new open source productivity app, that allows developers to be in the
  drivers seat. Unlike other solutions, there are no built in integrations, so
  every plugin has the full scope of what Zazu has to offer.
fixedNav: 'true' # true or false
themeColor: mint # teal, purple, green, blue, orange, purple, grey
siteurl: 'http://zazuapp.org'
branch: gh-pages

collections:
  packages:
    output: false
  documentation:
    output: true
    permalink: /documentation/:path/

gems:
  - jekyll-github-metadata
  - kramdown
  - rouge

# Social
twitterUsername: zazuapp
dribbbleUsername:
codepenUsername:
githubUsername: tinytacoteam

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages, _packages, _documentation]
exclude: [vendor, _site, CHANGELOG.md, LICENSE, README.md, .ruby-version]
sass:
  style: compressed
currentCommitSha: 26545d6bf17d83f7acea4d932100f18c6a511d61

currentAppVersion: v0.3.2
