environment:
  nodejs_version: "10"

os: unstable

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: $env:Path += ";C:\Program Files (x86)\NSIS"
  - choco install nsis -pre -y
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run cucumber
  - npm test

build: off
